services:
  - type: web
    name: shriyash-foods
    env: node
    plan: free
    buildCommand: npm install && npm run install-client && npm run build --prefix client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
